stages:
  - test

variables:
  PHP_VERSIONS: '7.4'

before_script:
  - apt-get update -qy
  - apt-get install -y php-cli php-xml
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer --version

test:
  stage: test
  script:
    - composer validate
    - composer install --prefer-dist --no-progress
    - composer run-script fix
    - phpcbf .; if [ $? -eq 1 ]; then exit 0; fi
    - parallel-lint . --exclude node_modules --exclude vendor
    - minus-x check .
    - phpcs -sp --cache .
    - phpunit
    - ! grep -E -r --binary-files=without-match --color=always --file=typos --exclude=typos --exclude=LICENSE.md --exclude-dir=.git --exclude-dir=vendor || true

push_changes:
  stage: test
  script:
    - |
      if ! git diff --exit-code --quiet; then
        git config --global user.name "gitlab-ci"
        git config --global user.email "gitlab-ci@gitlab.com"
        git remote set-url origin "https://x-access-token:$CI_JOB_TOKEN@gitlab.com/$CI_PROJECT_PATH.git"
        git checkout -b $CI_COMMIT_REF_NAME
        git add .
        git commit -am "CI: lint code to MediaWiki standards" -m "Check commit and GitLab CI/CD for more details"
        git pull origin $CI_COMMIT_REF_NAME --rebase
        git push --set-upstream origin $CI_COMMIT_REF_NAME
      else
        echo "No changes to commit"
      fi
  only:
    - merge_requests