<?php

wfLoadExtensions( [
	'AWS',
	'CreateWiki',
	'ManageWiki',
	'GlobalBlocking',
	'GlobalPreferences',
	// 'DiscordNotifications',
	'ConfirmEdit',
	'ConfirmEdit/Turnstile',
	'GlobalUserPage',
	'RemoveRedlinks',
	'WikiSEO',
	'NativeSvgHandler',
	'LinkSuggest',
	'DismissableSiteNotice',
	'GTag',
	'Cite',
	'TelepediaAds',
	'CentralAuth',
	'PortableInfobox',
	'ProtectSite',
	'ImportDump',
	'Echo',
	'CheckUser',
	'OAuth',
	'OATHAuth'
	'Nuke',
	'MultimediaViewer',
	'TemplateData',
	// 'SEO',
	'Scribunto',
	'AbuseFilter',
	'TelepediaMagic',
	'IPInfo',
	'SpamBlacklist',
	'RemovePII',
	'Renameuser',
	'StopForumSpam',
	'Interwiki'
] );
