<?php

final class GlobalPermissions {

    public static function modifyPermissionsAfterManageWiki() {
        global $wgGroupPermissions, $wgAddGroups;
        $wgGroupPermissions['saber'] = [
            'abusefilter-hidden-log' => true,
            'abusefilter-hide-log' => true,
            'abusefilter-log' => true,
            'abusefilter-log-detail' => true,
            'abusefilter-log-private' => true,
            'abusefilter-modify' => true,
            'abusefilter-modify-global' => true,
            'abusefilter-privatedetails' => true,
            'abusefilter-revert' => true,
            'abusefilter-view' => true,
            'abusefilter-view-private' => true,
            'bigdelete' => true,
            'block' => true,
            'blockemail' => true,
            'checkuser' => true,
            'checkuser-log' => true,
            'commentadmin' => true,
            'delete' => true,
            'read' => true,
            'deletedhistory' => true,
            'deletedtext' => true,
            'editprotected' => true,
            'globalblock' => true,
            'globalblock-exempt' => true,
            'globalblock-whitelist' => true,
            'ipblock-exempt' => true,
            'ipinfo' => true,
            'ipinfo-view-full' => true,
            'noratelimit' => true,
            'nuke' => true,
            'profilemanager' => true,
            'rollback' => true,
            'sboverride' => true,
            'sentinel' => true,
            'sentinel-view-logs' => true,
            'sfsblock-bypass' => true,
            'skipcaptcha' => true,
            'spamblacklistlog' => true,
            'suppressionlog' => true,
            'suppressredirect' => true,
            'suppressrevision' => true
        ];

    // Below is a list of every permission that is currently 
    // active on Telepedia; here to make sure that staff have all the
    // rights without relying on deferring to each wiki for inheritance
    // of rights like from user group since wikis may customise what those
    // groups can do.
    // @ April 2025 edition
    $wgGroupPermissions['staff'] = array_merge( $wgGroupPermissions['saber'], [
        'addvideo' => true,
        'analytics' => true,
        'apihighlimits' => true,
        'applychangetags' => true,
        'autoconfirmed' => true,
        'autocreateaccount' => true,
        'autopatrol' => true,
        'browsearchive' => true,
        'changetags' => true,
        'comment' => true,
        'comment-delete-own' => true,
        'commentlinks' => true,
        'createpage' => true,
        'createtalk' => true,
        'createwiki' => true,
        'cs-comment' => true,
        'cs-moderator-delete' => true,
        'cd-moderator-edit' => true,
        'delete-redirect' => true,
        'deletecargodata' => true,
        'deletechangetags' => true,
        'deletelogentry' => true,
        'deleterevision' => true,
        'edit' => true,
        'editcontentmodel' => true,
        'editinterface' => true,
        'editmyoptions' => true,
        'editmyprivateinfo' => true,
        'editmyusercss' => true,
        'editmyuserjs' => true,
        'editmyuserjson' => true,
        'editmyuserjsredirect' => true,
        'editmywatchlist' => true,
        'editprotected' => true,
        'edit-semiprotected' => true,
        'editsitecss' => true,
        'editsitejs' => true,
        'editusercss' => true,
        'edituserjs' => true,
        'edituserjson' => true,
        'gadgets-definition-edit' => true,
        'gadgets-edit' => true,
        'generate-random-hash' => true,
        'gtag-exempt' => true,
        'handle-import-dump-interwiki' => true,
        'handle-import-dump-requests' => true,
        'handle-pii' => true,
        'hideuser' => true,
        'import' => true,
        'importupload' => true,
        'interwiki' => true,
        'ipinfo-view-basic' => true,
        'ipinfo-view-log' => true,
        'maintenance' => true,
        'manage-all-push-subscriptions' => true,
        'managechangetags' => true,
        'managewiki' => true,
        'managewiki-core' => true,
        'managewiki-editdefault' => true,
        'managewiki-extensions' => true,
        'managewiki-namespaces' => true,
        'managewiki-permissions' => true,
        'managewiki-restricted' => true,
        'managewiki-settings' => true,
        'mass-upload' => true,
        'masseditregex' => true,
        'mergehistory' => true,
        'minoredit' => true,
        'monitor-file-storage' => true,
        'move' => true,
        'move-categorypage' => true,
        'move-rootuserpage' => true,
        'move-subpages' => true,
        'movefile' => true,
        'mwoauthmanageconsumer' => true,
        'mwoauthmanagemygrants' => true,
        'mwoauthproposeconsumer' => true,
        'mwoauthsuppress' => true,
        'mwoauthupdateownconsumer' => true,
        'mwoauthviewprivate' => true,
        'mwoauthviewsuppressed' => true,
        'noanalytics' => true,
        'nominornewtalk' => true,
        'oathauth-enable' => true,
        'oathauth-verify-user' => true,
        'oathauth-view-log' => true,
        'override-export-depth' => true,
        'pagelang' => true,
        'patrol' => true,
        'patrolmarks' => true,
        'protect' => true,
        'protectsite' => true,
        'purge' => true,
        'recreatecargodata' => true,
        'renameuser' => true,
        'replacetext' => true,
        'request-import-dump' => true,
        'requestwiki' => true,
        'reupload' => true,
        'reupload-own' => true,
        'reupload-shared' => true,
        'runcargoqueries' => true,
        'search_log' => true,
        'sendemail' => true,
        'seo' => true,
        'siteadmin' => true,
        'tboverride' => true,
        'tboverride-account' => true,
        'titleblacklistlog' => true,
        'unblockself' => true,
        'undelete' => true,
        'unwatchedpages' => true,
        'upload' => true,
        'upload_by_url' => true,
        'upwizcampaigns' => true,
        'userrights' => true,
        'userrights-interwiki' => true,
        'view-private-import-dump-requests' => true,
        'viewmypivateinfo' => true,
        'viewmywatchlist' => true,
        'viewsuppressed' => true,
        'writeapi' => true,
        'configcentre' => true,
        'configcentre-restricted' => true,
        'editinterface-platform' => true,
    ]);

    $wgGroupPermissions['global-bot'] = [
        'bot' => true,
        'editsemiprotected' => true,
        'skipcaptcha' => true
    ];

    $wgAddGroups['staff']['sentinel'] = true;
    $wgAddGroups['staff']['checkuser'] = true;

    // don't care, thank you
    unset( $wgGroupPermissions['steward'] );
    }
}

