<?php

wfLoadExtensions( [
	'AWS',
	'Cloudflare',
	'ConfirmEdit',
	'ConfirmEdit/Turnstile',
	'WikiSEO',
	'LinkSuggest',
	'GTag',
	'Cite',
	'TelepediaAds',
	'PortableInfobox',
	'ProtectSite',
	'Echo',
	'Purge',
	'CheckUser',
	'Nuke',
	'MultimediaViewer',
	'TemplateData',
	'Scribunto',
	'AbuseFilter',
	'TelepediaMagic',
	'IPInfo',
	'SpamBlacklist',
	'StopForumSpam',
	'Interwiki',
	'OAuth',
	'GlobalPermissions',
	'GlobalBlocking',
	'UserProfileV2',
	'UAM',
	'Sentinel',
	'TelepediaCore',
	'ConfigCentre',
	'ToastNotifications',
	'SitemapOnTheFly',
	'MissingWiki',
	'CreateWiki',
	'GlobalPreferences',
	'RequestToBeForgotten'
] );

wfLoadExtension( 'Parsoid', "$IP/vendor/wikimedia/parsoid/extension.json" );