<?php

wfLoadExtensions( [
	'AWS',
	'AntiSpoof',
	'CreateWiki',
	'ManageWiki',
	'GlobalBlocking',
	'GlobalPreferences',
	'ConfirmEdit',
	'ConfirmEdit/Turnstile',
	'GlobalUserPage',
	'RemoveRedlinks',
	'WikiSEO',
	'NativeSvgHandler',
	'LinkSuggest',
	'DismissableSiteNotice',
	'GTag',
	'Cite',
	'TelepediaAds',
	'CentralAuth',
	'PortableInfobox',
	'ProtectSite',
	//'ImportDump',
	'Echo',
	'Purge',
	'CheckUser',
	'OAuth',
	'OATHAuth',
	'Nuke',
	'MultimediaViewer',
	'TemplateData',
	// 'SEO',
	'Scribunto',
	'AbuseFilter',
	'TelepediaMagic',
	'IPInfo',
	'SpamBlacklist',
	//'RemovePII',
	'Renameuser',
	'StopForumSpam',
	'Interwiki',
	'RedisCache',
	'Sentinel',
	//'SEOTweaks',
	'UserProfileV2'
] );
