server {
    listen 8080 default_server;
    server_name _;
    root /srv/mediawiki;

    set_real_ip_from 10.42.0.0/16;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    add_header X-Forwarded-Proto "https";
    set $fastcgi_server_name $host;
    client_max_body_size 100m;

    location = /ads.txt {
        return 301 https://config.playwire.com/dyn_ads/1025055/74539/ads.txt;
    }

    rewrite "^/(?:[a-z]{2,3}(?:-[a-z-]{2,12})?/)?robots\.txt$" /robots.php last;
    rewrite "^/(?:[a-z]{2,3}(?:-[a-z-]{2,12})?/)?api\.php(.*)" /api.php$1 break;
    rewrite "^/(?:[a-z]{2,3}(?:-[a-z-]{2,12})?/)?rest\.php(/.*)" /rest.php$1 break;
    rewrite "^/(?:[a-z]{2,3}(?:-[a-z-]{2,12})?/)?(index|load|opensearch_desc|img_auth|info)\.php(.*)" /$1.php$2 break;
    rewrite "^/(?:[a-z]{2,3}(?:-[a-z-]{2,12})?/)?wiki/(.*)" /index.php?title=$1 break;
    rewrite "^/(?:[a-z]{2,3}(?:-[a-z-]{2,12})?/?)?$" /index.php break;
    rewrite "^/(?:[a-z]{2,3}(?:-[a-z-]{2,12})?/)?(__cb\d+/)?(skins|resources|extensions)/(.+)" /$2/$3 break;

    location = /robots.php {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME /srv/config/entrypoints/robots.php;
        fastcgi_param REQUEST_SCHEME https;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param SERVER_NAME $fastcgi_server_name;
    }

    location ~ "^/(?:[a-z]{2,3}(?:-[a-z-]{2,12})?/)?sitemap(-NS-\d+(?:-part-\d+)?)?\.xml$" {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME /srv/config/entrypoints/sitemap.php;
        fastcgi_param REQUEST_SCHEME https;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param SERVER_NAME $fastcgi_server_name;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param QUERY_STRING $query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param REQUEST_SCHEME https;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param SERVER_NAME $fastcgi_server_name;
        fastcgi_read_timeout 240;
    }

    location ~ ^/resources/(assets|lib|src) {
        try_files $uri =404;
        add_header Cache-Control "public";
        expires 7d;
    }

    location ~ ^/(skins|extensions)/.+\.(css|js|gif|jpg|jpeg|png|svg|wasm|ttf|woff|woff2)$ {
        try_files $uri =404;
        add_header Cache-Control "public";
        expires 7d;
    }

    location ~ ^/(COPYING|CREDITS)$ { 
        default_type text/plain; 
    }

    location ~ ^/(config|lib|serialized|tests|includes|cache|maintenance|languages) {
        return 403;
    }

    location / { return 404; }
}
